
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/components/progressview/Props.h>
#include <react/renderer/components/image/conversions.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook::react {

RNCProgressViewProps::RNCProgressViewProps(
    const PropsParserContext &context,
    const RNCProgressViewProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    progressViewStyle(convertRawProp(context, rawProps, "progressViewStyle", sourceProps.progressViewStyle, {RNCProgressViewProgressViewStyle::Default})),
    progress(convertRawProp(context, rawProps, "progress", sourceProps.progress, {0.0})),
    progressTintColor(convertRawProp(context, rawProps, "progressTintColor", sourceProps.progressTintColor, {})),
    trackTintColor(convertRawProp(context, rawProps, "trackTintColor", sourceProps.trackTintColor, {})),
    progressImage(convertRawProp(context, rawProps, "progressImage", sourceProps.progressImage, {})),
    trackImage(convertRawProp(context, rawProps, "trackImage", sourceProps.trackImage, {})),
    isIndeterminate(convertRawProp(context, rawProps, "isIndeterminate", sourceProps.isIndeterminate, {false}))
      {}

} // namespace facebook::react
